// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/goqueue/v1/job.proto

package goqueuev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	RunAt         int64                  `protobuf:"varint,5,opt,name=run_at,json=runAt,proto3" json:"run_at,omitempty"` // unix timestamp; 0 = now
	MaxRetries    int32                  `protobuf:"varint,6,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_proto_goqueue_v1_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goqueue_v1_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_proto_goqueue_v1_job_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *Job) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Job) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Job) GetRunAt() int64 {
	if x != nil {
		return x.RunAt
	}
	return 0
}

func (x *Job) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type EnqueueJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueJobRequest) Reset() {
	*x = EnqueueJobRequest{}
	mi := &file_proto_goqueue_v1_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueJobRequest) ProtoMessage() {}

func (x *EnqueueJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goqueue_v1_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueJobRequest.ProtoReflect.Descriptor instead.
func (*EnqueueJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_goqueue_v1_job_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueJobRequest) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type EnqueueJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueJobResponse) Reset() {
	*x = EnqueueJobResponse{}
	mi := &file_proto_goqueue_v1_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueJobResponse) ProtoMessage() {}

func (x *EnqueueJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goqueue_v1_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueJobResponse.ProtoReflect.Descriptor instead.
func (*EnqueueJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_goqueue_v1_job_proto_rawDescGZIP(), []int{2}
}

func (x *EnqueueJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_proto_goqueue_v1_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goqueue_v1_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_goqueue_v1_job_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_proto_goqueue_v1_job_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goqueue_v1_job_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_goqueue_v1_job_proto_rawDescGZIP(), []int{4}
}

func (x *GetJobStatusResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_proto_goqueue_v1_job_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goqueue_v1_job_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_goqueue_v1_job_proto_rawDescGZIP(), []int{5}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_proto_goqueue_v1_job_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goqueue_v1_job_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_goqueue_v1_job_proto_rawDescGZIP(), []int{6}
}

func (x *CancelJobResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

var File_proto_goqueue_v1_job_proto protoreflect.FileDescriptor

const file_proto_goqueue_v1_job_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/goqueue/v1/job.proto\x12\n" +
	"goqueue.v1\"\xb1\x01\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x15\n" +
	"\x06run_at\x18\x05 \x01(\x03R\x05runAt\x12\x1f\n" +
	"\vmax_retries\x18\x06 \x01(\x05R\n" +
	"maxRetries\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"6\n" +
	"\x11EnqueueJobRequest\x12!\n" +
	"\x03job\x18\x01 \x01(\v2\x0f.goqueue.v1.JobR\x03job\"+\n" +
	"\x12EnqueueJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"9\n" +
	"\x14GetJobStatusResponse\x12!\n" +
	"\x03job\x18\x01 \x01(\v2\x0f.goqueue.v1.JobR\x03job\")\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"1\n" +
	"\x11CancelJobResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled2\xf6\x01\n" +
	"\n" +
	"JobService\x12K\n" +
	"\n" +
	"EnqueueJob\x12\x1d.goqueue.v1.EnqueueJobRequest\x1a\x1e.goqueue.v1.EnqueueJobResponse\x12Q\n" +
	"\fGetJobStatus\x12\x1f.goqueue.v1.GetJobStatusRequest\x1a .goqueue.v1.GetJobStatusResponse\x12H\n" +
	"\tCancelJob\x12\x1c.goqueue.v1.CancelJobRequest\x1a\x1d.goqueue.v1.CancelJobResponseB;Z9github.com/abishekP101/goqueue/proto/goqueue/v1;goqueuev1b\x06proto3"

var (
	file_proto_goqueue_v1_job_proto_rawDescOnce sync.Once
	file_proto_goqueue_v1_job_proto_rawDescData []byte
)

func file_proto_goqueue_v1_job_proto_rawDescGZIP() []byte {
	file_proto_goqueue_v1_job_proto_rawDescOnce.Do(func() {
		file_proto_goqueue_v1_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_goqueue_v1_job_proto_rawDesc), len(file_proto_goqueue_v1_job_proto_rawDesc)))
	})
	return file_proto_goqueue_v1_job_proto_rawDescData
}

var file_proto_goqueue_v1_job_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_goqueue_v1_job_proto_goTypes = []any{
	(*Job)(nil),                  // 0: goqueue.v1.Job
	(*EnqueueJobRequest)(nil),    // 1: goqueue.v1.EnqueueJobRequest
	(*EnqueueJobResponse)(nil),   // 2: goqueue.v1.EnqueueJobResponse
	(*GetJobStatusRequest)(nil),  // 3: goqueue.v1.GetJobStatusRequest
	(*GetJobStatusResponse)(nil), // 4: goqueue.v1.GetJobStatusResponse
	(*CancelJobRequest)(nil),     // 5: goqueue.v1.CancelJobRequest
	(*CancelJobResponse)(nil),    // 6: goqueue.v1.CancelJobResponse
}
var file_proto_goqueue_v1_job_proto_depIdxs = []int32{
	0, // 0: goqueue.v1.EnqueueJobRequest.job:type_name -> goqueue.v1.Job
	0, // 1: goqueue.v1.GetJobStatusResponse.job:type_name -> goqueue.v1.Job
	1, // 2: goqueue.v1.JobService.EnqueueJob:input_type -> goqueue.v1.EnqueueJobRequest
	3, // 3: goqueue.v1.JobService.GetJobStatus:input_type -> goqueue.v1.GetJobStatusRequest
	5, // 4: goqueue.v1.JobService.CancelJob:input_type -> goqueue.v1.CancelJobRequest
	2, // 5: goqueue.v1.JobService.EnqueueJob:output_type -> goqueue.v1.EnqueueJobResponse
	4, // 6: goqueue.v1.JobService.GetJobStatus:output_type -> goqueue.v1.GetJobStatusResponse
	6, // 7: goqueue.v1.JobService.CancelJob:output_type -> goqueue.v1.CancelJobResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_goqueue_v1_job_proto_init() }
func file_proto_goqueue_v1_job_proto_init() {
	if File_proto_goqueue_v1_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_goqueue_v1_job_proto_rawDesc), len(file_proto_goqueue_v1_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_goqueue_v1_job_proto_goTypes,
		DependencyIndexes: file_proto_goqueue_v1_job_proto_depIdxs,
		MessageInfos:      file_proto_goqueue_v1_job_proto_msgTypes,
	}.Build()
	File_proto_goqueue_v1_job_proto = out.File
	file_proto_goqueue_v1_job_proto_goTypes = nil
	file_proto_goqueue_v1_job_proto_depIdxs = nil
}
